// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSvWArAaMtMDagp-P-g810FBG6cxNw7ls',
    appId: '1:662984654457:web:95c43dfaba680057ad1ea8',
    messagingSenderId: '662984654457',
    projectId: 'petagram-f6218',
    authDomain: 'petagram-f6218.firebaseapp.com',
    storageBucket: 'petagram-f6218.firebasestorage.app',
    measurementId: 'G-MYJJF6YFD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDurH-jfkMpPCJcvXL9G9Y-BU85Bj_I3SM',
    appId: '1:662984654457:android:0c05839e2079cf20ad1ea8',
    messagingSenderId: '662984654457',
    projectId: 'petagram-f6218',
    storageBucket: 'petagram-f6218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOe_G7b15ycILRnURaUD_PdN_MwE68Cus',
    appId: '1:662984654457:ios:4edcf5cd69077a52ad1ea8',
    messagingSenderId: '662984654457',
    projectId: 'petagram-f6218',
    storageBucket: 'petagram-f6218.firebasestorage.app',
    iosBundleId: 'com.example.petagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOe_G7b15ycILRnURaUD_PdN_MwE68Cus',
    appId: '1:662984654457:ios:4edcf5cd69077a52ad1ea8',
    messagingSenderId: '662984654457',
    projectId: 'petagram-f6218',
    storageBucket: 'petagram-f6218.firebasestorage.app',
    iosBundleId: 'com.example.petagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSvWArAaMtMDagp-P-g810FBG6cxNw7ls',
    appId: '1:662984654457:web:32bca4c38dc62b0aad1ea8',
    messagingSenderId: '662984654457',
    projectId: 'petagram-f6218',
    authDomain: 'petagram-f6218.firebaseapp.com',
    storageBucket: 'petagram-f6218.firebasestorage.app',
    measurementId: 'G-Q3XXNW806F',
  );
}
